//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanQLDA
    {
        public int ID { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public string Mabanqlda { get; set; }
        public string Tenbanqlda { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mota { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    }
}
